### ISSUE TITLE
int as argument for Sender's functions doesn't work.

### ISSUE THREAD

**Issue by luckydonald** [luckydonald/pytg#32]
int as argument does not work.
Fails concatenating the final command string ```arg_string = " ".join([u(x) for x in args])```
```python
s.history('user_name', 10)
# log/stacktrace shows:
DEBUG:pytg.sender:Parsing history: Argument user_name - <user> (needed)
DEBUG:pytg.sender:Parsing history: Argument 10 - [limit] (needed)
DEBUG:pytg.sender:Skipping missing optional parameter #2 [offset] (type NonNegativeNumber) in function history.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/pytg/pytg/sender.py", line 548, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/path/to/pytg/pytg/sender.py", line 252, in execute_function
    result = self._do_command(command_name, new_args, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect, enable_preview=enable_preview, reply_id=reply_id)
  File "/path/to/pytg/pytg/sender.py", line 356, in _do_command
    arg_string = " ".join([u(x) for x in args])
TypeError: sequence item 1: expected str instance, int found
>>> from pytg.sender import Sender ; import logging
>>> s.execute_function('history', 'user_name', 10)
DEBUG:pytg.sender:Parsing history: Argument user_name - <user> (needed)
DEBUG:pytg.sender:Parsing history: Argument 10 - [limit] (needed)
DEBUG:pytg.sender:Skipping missing optional parameter #2 [offset] (type NonNegativeNumber) in function history.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/pytg/pytg/sender.py", line 252, in execute_function
    result = self._do_command(command_name, new_args, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect, enable_preview=enable_preview, reply_id=reply_id)
  File "/path/to/pytg/pytg/sender.py", line 356, in _do_command
    arg_string = " ".join([u(x) for x in args])
TypeError: sequence item 1: expected str instance, int found```

**Comment by luckydonald** [comment]
from #31

**Comment by luckydonald** [comment]
Fixed

**Comment by ZeroDivisionError** [comment]
Still broken for python 3. Because python-utils/luckydonaldUtils/encoding.py does not include commit with this bugfix.

**Comment by luckydonald** [comment]
Eargh

**Comment by luckydonald** [comment]
Please update ```luckydonald-utils``` to ```v0.017``` or newer.
 *```v0.017``` Package is called ```0.17``` in pip.*

**Comment by luckydonald** [comment]
I assume this as fixed and working.
